### ISSUE TITLE
failt to start

### ISSUE THREAD

**Issue by leblitzdick** [shesek/bitcoinuri#1]
Hi,
hope you still watching this and help me...

I get an error at starting the Program and have no idea...

~/ ฿>  PORT=3000 npm start

> bitcoinuri@0.2.0 start /home/bitcoin/bitcoinuri
> node server.js

/home/bitcoin/bitcoinuri/util.js:5
    , { PaymentRequest, PaymentDetails } = require('bcoin').bip70
        ^

TypeError: Cannot destructure property `PaymentRequest` of 'undefined' or 'null'.
    at Object.<anonymous> (/home/bitcoin/bitcoinuri/util.js:5:60)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bitcoin/bitcoinuri/server.js:3:46)
    at Module._compile (module.js:653:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bitcoinuri@0.2.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcoinuri@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcoin/.npm/_logs/2019-02-15T07_27_51_316Z-debug.log

and the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/lib/nodejs/bin/node',
1 verbose cli   '/usr/local/lib/nodejs/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bitcoinuri@0.2.0~prestart: bitcoinuri@0.2.0
6 info lifecycle bitcoinuri@0.2.0~start: bitcoinuri@0.2.0
7 verbose lifecycle bitcoinuri@0.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle bitcoinuri@0.2.0~start: PATH: /usr/local/lib/nodejs/lib/node_modules/npm/node_mo
dules/npm-lifecycle/node-gyp-bin:/home/bitcoin/bitcoinuri/node_modules/.bin:/usr/local/lib/nodejs/bi
n:/usr/local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr
/local/games:/usr/games:/usr/local/bin/sas:/home/bitcoin/go/bin:.:/home/bitcoin/dotnet
9 verbose lifecycle bitcoinuri@0.2.0~start: CWD: /home/bitcoin/bitcoinuri
10 silly lifecycle bitcoinuri@0.2.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle bitcoinuri@0.2.0~start: Returned: code: 1  signal: null
12 info lifecycle bitcoinuri@0.2.0~start: Failed to exec start script
13 verbose stack Error: bitcoinuri@0.2.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/nodejs/lib/node_modules/npm/node_mo
dules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/nodejs/lib/node_modules/npm/node_mo
dules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid bitcoinuri@0.2.0
15 verbose cwd /home/bitcoin/bitcoinuri
16 verbose Linux 4.14.79-v7+
17 verbose argv "/usr/local/lib/nodejs/bin/node" "/usr/local/lib/nodejs/bin/npm" "start"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error bitcoinuri@0.2.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the bitcoinuri@0.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thanks

**Comment by shesek** [comment]
Did you run `npm install` first? It looks like its pulling a different incompatible version of `bcoin` from somewhere, which shouldn't happen if `bitcoinuri` installed its dependencies to the local `node_modules` directory.

**Comment by leblitzdick** [comment]
yes i do, but there were some error messages at the beginning...i just repeated the whole installation and send you the log from the console of the install command:

[console log.txt](https://github.com/shesek/bitcoinuri/files/2871422/console.log.txt)

by the way, my first node installation was version 8.15 now i upgrade to 10.15.1, but the errors are the same....
